重写find—files, search-string, 得到更加方便的使用

diff --git a/scripts/fzf/search-string b/scripts/fzf/search-string
--- a/scripts/fzf/search-string
+++ b/scripts/fzf/search-string
@@ -1,34 +1,83 @@
 #!/bin/env bash
 
+# 1. 能够解析常用的参数
+# 2. 接受目录或文件
+# 3. 能够在fzf过滤时，解释--iglob --hidden --no-ignore
+# 4. 同find-files，尽可能解释用户传入的参数
+# 5. 解决了\b的转义问题
+
 help() {
-    >&2 echo 'usage: ss [OPTIONS] [init_query] [DIRECTORIES or Files]
+    >&2 echo 'usage: ss [OPTIONS] [pattern] [DIRECTORIES or Files]
 
     OPTIONS:
         -t file types,  Comma-separated
         -T file types(not),  Comma-separated
-        -D int max-depth
+        -d int max-depth
         -H bool --hidden
         -I bool --no-ignore 
-        -q first param is not a init_query
+        -q Cancel the first n matching file names (Optional, default 1)
         -w world regex
-        -u[uu]
+        -u[uu] (Optional default -u)
+        -O output to stdout
         -P no-popup 
         -F full-window
+
+        --help 
+        --split Explain the parameters passed in by the user as much as possible \
+            priority: file_or_directory > max_depth > type > pattern (Optional default all)
+        --extra-args pass -> rg
 
     KEYBINDINGS:
         ctrl-s horizontal direction splitw
         ctrl-v vertical direction splitw
-        alt-e fzf-tmux-menu splitw
+        ctrl-o fzf-tmux-menu splitw
+        alt-e subshell editor
+        alt-enter open dirname file
     '
 }
-__split_dirs_and_files() {
+
+__split() {
     while read -d " " -r entry; do
-        if [[ -d $entry ]]; then
-            Directories+="$entry "
-        else
-            Files+="$entry "
-        fi
+        # echo "|$entry|"
+        # 1 解释为目录和文件
+        __split_directory_or_file && continue
+        # 2 解释为最大深度
+        [[ $flag_split -eq 1 || " $flag_split " == *" depth "* ]] && __split_max_depth && continue
+        # 3 解释为文件类型
+        [[ $flag_split -eq 1 || " $flag_split " == *" type "* ]] && __split_type && continue
+        # 4 解释为正则
+        [[ $flag_split -eq 1 || " $flag_split " == *" pattern "* ]] && __split_pattern || exit 1
     done <&0
+    set +x
+}
+__split_pattern() {
+    [[ -n $Pattern ]] && {
+        echo "$entry error, pattern is exists" &> /dev/tty
+        return 1
+    }
+    Pattern=$entry
+}
+__split_max_depth() {
+    [[ "$entry" =~ ^[[:digit:]]{1,2}$ ]] && flag_max_depth=$entry || return 1
+}
+__split_type() {
+    [[ "$entry" =~ ,$ ]] && {
+        while read -d "," -r type; do
+            flag_other_args+="--type=$type "
+        done <<< "$entry"
+        return 0
+    }
+    [[ "$entry" =~ ^, ]] && {
+        while read -d "," -r type; do
+            flag_other_args+="--type-not=$type "
+        done <<< "${entry:1},"
+        return 0
+    }
+    return 1
+}
+__split_directory_or_file() {
+    { [[ ! -e "$entry" ]] || ((flag_q-- > 0)); } && return 1
+    [[ -d $entry ]] && Directories+="$entry " || Files+="$entry "
 }
 
 __exec_action() {
@@ -44,18 +93,18 @@ __exec_action() {
     elif [[ "${trigger_key}" == "ctrl-v" ]]; then
         tmux splitw -bh zsh -c "${EDITOR} $file +$line_number"
     elif [[ "${trigger_key}" == "ctrl-o" ]]; then
-        "$CUSTOM_HOME/scripts/tmux/tmux-menu" $(realpath $file) +$line_number
+        "$CUSTOM_HOME/scripts/tmux/tmux-menu" "$(realpath "$file")" "+$line_number"
     elif [[ "${trigger_key}" == "alt-enter" ]]; then
-        "${EDITOR}" "$(dirname $file)" > /dev/tty < /dev/tty
+        "${EDITOR}" "$(dirname "$file")" > /dev/tty < /dev/tty
     else
-        ${EDITOR} $file +$line_number > /dev/tty < /dev/tty
+        ${EDITOR} "$file" "+$line_number" > /dev/tty < /dev/tty
     fi
 }
 
 main() {
-    typeset flag_P flag_F flag_q flag_max_depth flag_other_args
+    typeset flag_P flag_F flag_O flag_q flag_max_depth flag_split flag_other_args
 
-    args=$(getopt -o D:t:T:u::qwHIPF -l help -n "$0" -- "$@")
+    args=$(getopt -o d:t:T:u::q::wHIPFO -l help,split::,extra-args: -n "$0" -- "$@")
     eval set -- "$args"
 
     while true; do
@@ -64,9 +113,21 @@ main() {
             help
             exit 0
             ;;
-        -q)
-            flag_q=1
+        --split)
+            flag_split=${2:-1}
+            shift 2
+            ;;
+        --extra-args)
+            flag_other_args+="$2 "
+            shift 2
+            ;;
+        -O)
+            flag_O=1
             shift
+            ;;
+        -q)
+            flag_q=${2:-1}
+            shift 2
             ;;
         -w)
             flag_other_args+="-w "
@@ -104,7 +165,7 @@ main() {
             flag_other_args+="--no-ignore "
             shift
             ;;
-        -D)
+        -d)
             flag_max_depth=$2
             shift 2
             ;;
@@ -122,37 +183,35 @@ main() {
     [[ -v TMUX && -z $flag_P ]] && command -v fzf-tmux &> /dev/null &&
         if [[ $flag_F ]]; then fzf_bin="fzf-tmux -p100%,100%"; else fzf_bin="fzf-tmux $FZF_GREP_TMUX_OPTS"; fi
 
-    typeset Directories Files Results
-    typeset cmd init_query opts file_r file_f
+    typeset Directories Files Results Pattern
+    typeset cmd opts file_r file_f file_pattern
     typeset transform_change transform_toggle init_bind
 
-    if [[ -z $flag_q ]]; then
-        init_query=$1
-        shift
-    fi
-    [[ $* ]] && __split_dirs_and_files <<< "$* "
+    [[ $* ]] && __split <<< "$* "
+    [[ "$Directories" =~ ^[[:blank:]]*\.[[:blank:]]*$ ]] && Directories=
 
     cmd="command rg --line-number --no-heading --color=always --smart-case \
           --max-depth=${flag_max_depth:-6} ${flag_other_args}"
     file_r=/tmp/f-$$
     file_f=/tmp/r-$$
-    trap "command rm -f $file_r $file_f" EXIT SIGINT SIGTERM
+    file_pattern=/tmp/pattern-$$
+    # shellcheck disable=SC2064
+    trap "command rm -f $file_r $file_f $file_pattern" EXIT SIGINT SIGTERM
 
     transform_change="
     setopt extended_glob
-    typeset args files
+    typeset args
     [[ \$FZF_QUERY == *--* ]] && for elem in \${(s/ /)\${FZF_QUERY##*--}}; do 
         case \$elem in
-            H) args+=\\\"--hidden \\\"
-            ;;
-            I) args+=\\\"--no-ignore \\\"
-            ;;
-            *) args+=\\\"'--iglob=\$elem' \\\"
-            ;;
+            H) args+=\\\"--hidden \\\" ;;
+            I) args+=\\\"--no-ignore \\\" ;;
+            [[:digit:]]) args+=\\\"--max-depth=\$elem \\\" ;;
+            *) args+=\\\"'--iglob=\$elem' \\\" ;;
         esac
     done
-    echo \\\"reload:sleep 0.1; ${cmd} \$args '\${FZF_QUERY% ##--*}' ${Directories} ${Files} || true\\\"
+    echo \\\"transform-query(echo -E \\\{q} > $file_pattern; sed 's/[[:blank:]]*--.*$//' $file_pattern)+reload(${cmd} \$args \\\{q} ${Directories} ${Files} || true)+transform-query(cat $file_pattern)\\\"
     "
+
     transform_toggle="
     if [[ ! \$FZF_PROMPT =~ Rg ]]; then
         echo \\\"rebind(change)+change-prompt(Rg> )+disable-search+transform-query:echo -E \\\{q} > $file_f; cat $file_r\\\"
@@ -160,31 +219,34 @@ main() {
         echo \\\"unbind(change)+change-prompt(Fzf> )+enable-search+transform-query:echo -E \\\{q} > $file_r; cat $file_f\\\"
     fi
     "
-    init_bind="--bind=\"start:reload:${cmd} \{q} ${Directories} ${Files}\""
+    init_bind="
+    --query '$Pattern'
+    --bind=\"start:reload:${cmd} \{q} ${Directories} ${Files}\"
+    "
 
     opts="
     $FZF_DEFAULT_OPTS
     --disabled +m
-    --query \"$init_query\" --prompt \"Rg> \"
+    --prompt \"Rg> \"
     --exact
-    ${init_query:+${init_bind}}
+    ${Pattern:+${init_bind}}
     --bind \"change:transform:$transform_change\"
     --bind \"ctrl-t:transform:$transform_toggle\"
     --delimiter :
-    --header \"keybindings: C-t(toggle fzf|rg), C-s(hsp), C-v(vsp), C-o(fzf-tmux-menu), A-e(execute editor),\"
+    --header \"keybindings: C-t, C-s, C-v, C-o, A-e, A-alt\"
     --preview 'bat --style=numbers,header,changes,snip --color=always --highlight-line {2} -- {1}'
     --preview-window 'default:right:60%:~1:+{2}+3/2:border-left'
-    --expect \"ctrl-s,ctrl-v,ctrl-o\"
+    --expect \"ctrl-s,ctrl-v,ctrl-o,alt-enter\"
     --bind=\"alt-e:execute(${EDITOR} {1} +{2} > /dev/tty < /dev/tty)\"
     --bind=\"ctrl-s:accept\"
     --bind=\"ctrl-v:accept\"
     --bind=\"ctrl-o:accept\"
     --bind=\"enter:accept\"
+    --bind=\"alt-enter:accept\"
     "
 
     Results=$(: | FZF_DEFAULT_OPTS=$opts ${fzf_bin:-fzf} | grep -v "^$")
 
-    [[ $Results ]] && __exec_action
+    [[ $Results ]] && if [[ $flag_O ]]; then echo "$Results"; else __exec_action; fi
 }
 main "$@"
-# parse_directory_mark "$@"
