1. add no-popup 2. modify README.md

diff --git a/fzf/directores-actions b/fzf/directores-actions
--- a/fzf/directores-actions
+++ b/fzf/directores-actions
@@ -13,6 +13,13 @@ zoxide_directores() {
     action=/tmp/$$
     [[ -e $action ]] && exit 1
     trap "command rm -f $action" EXIT SIGINT SIGTERM
+
+    action_ff="execute($CUSTOM_HOME/scripts/fzf/find-files ${fzf_bin:---no-popup} {+})"
+    action_ft="transform:echo f > $action; echo accept"
+    action_sf="execute($CUSTOM_HOME/scripts/fzf/search-string ${fzf_bin:---no-popup} {+})"
+    action_st="transform:echo g > $action; echo accept"
+    action_e="execute(${EDITOR} {+} > /dev/tty < /dev/tty)"
+
     readarray -t directores < <(
         zoxide query --list | lscolors |
             ${fzf_bin:-fzf} \
@@ -20,11 +27,12 @@ zoxide_directores() {
                 --exit-0 --header-first \
                 --exact --scheme history --tiebreak "end,chunk,index" \
                 --header "keybindings: C-f(find files), C-g(grep string), C-s(hsp), C-v(vsp), A-e(fzf-tmux-menu), Enter(select or new file)" \
-                --bind="ctrl-f:transform:echo f > $action; echo accept" \
-                --bind="ctrl-g:transform:echo g > $action; echo accept" \
+                --bind="ctrl-f:transform:[ \"${fzf_bin}\" ] && echo \"$action_ft\" || echo \"$action_ff\"" \
+                --bind="ctrl-g:transform:[ \"${fzf_bin}\" ] && echo \"$action_st\" || echo \"$action_sf\"" \
                 --bind="ctrl-s:transform:echo h > $action; echo accept" \
                 --bind="ctrl-v:transform:echo v > $action; echo accept" \
-                --bind="alt-e:transform:echo  m > $action; echo accept" \
+                --bind="ctrl-o:transform:echo  m > $action; echo accept" \
+                --bind="alt-e:transform:[[ \"${fzf_bin}\" ]] && echo \"ignore\" || echo \"${action_e}\"" \
                 --bind="enter:accept-or-print-query"
     )
 }
@@ -41,9 +49,10 @@ exec_action() {
         if [[ "${flag}" =~ ^(h|v)$ ]]; then
             tmux splitw "-b${flag}" zsh -c "${EDITOR} ${directores}"
         elif [[ "${flag}" == m ]]; then
-            $CUSTOM_HOME/scripts/tmux/tmux-menu "${directores}"
+            $CUSTOM_HOME/scripts/tmux/tmux-menu $(realpath "${directores}")
         else
-            ${EDITOR} "${directores}"
+            echo "${directores[@]}"
+            ${EDITOR} ""
 
         fi
     fi
@@ -53,6 +62,28 @@ main() {
     [[ -v TMUX && $(command -v fzf-tmux) ]] && fzf_bin="fzf-tmux ${FZF_TMUX_OPTS}"
 
     typeset directores action
+
+    typeset args
+
+    args=$(getopt -o z -l no-popup -n "$0" -- "$@")
+    eval set -- "$args"
+
+    while true; do
+        case $1 in
+        --no-popup)
+            fzf_bin=
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "arg error"
+            exit 1
+            ;;
+        esac
+    done
 
     zoxide_directores "$@"
 
diff --git a/fzf/find-gitfiles b/fzf/find-gitfiles
--- a/fzf/find-gitfiles
+++ b/fzf/find-gitfiles
@@ -24,6 +24,9 @@ fzf_search() {
     action=/tmp/$$
     [[ -e $action ]] && exit 1
     trap "command rm -f $action" EXIT SIGINT SIGTERM
+
+    action_e="execute(${EDITOR} {+} > /dev/tty < /dev/tty)"
+
     readarray -t files < <(
         git ls-files --with-tree=HEAD "${git_flags[@]}" | lscolors | ${fzf_bin:-fzf} \
             --prompt="Gitfiles> " ${filter_query:+--filter "${filter_query}"} \
@@ -32,7 +35,8 @@ fzf_search() {
             --header "keybindings: C-s(hsp), C-v(vsp), A-e(fzf-tmux-menu), Enter(select or new file)" \
             --bind="ctrl-s:transform:echo h > $action; echo accept" \
             --bind="ctrl-v:transform:echo v > $action; echo accept" \
-            --bind="alt-e:transform:echo m  > $action; echo accept" \
+            --bind="ctrl-o:transform:echo m > $action; echo accept" \
+            --bind="alt-e:transform:[[ \"${fzf_bin}\" ]] && echo \"ignore\" || echo \"${action_e}\"" \
             --bind="enter:accept-or-print-query" | sed -n "${filter_query:+1}p"
     )
 
@@ -45,7 +49,8 @@ exec_action() {
     if [[ "${flag}" =~ ^(h|v)$ ]]; then
         tmux splitw "-b${flag}" zsh -c "${EDITOR} ${files[*]}"
     elif [[ "${flag}" == m ]]; then
-        $CUSTOM_HOME/scripts/tmux/tmux-menu "${files[*]}"
+        set -x
+        $CUSTOM_HOME/scripts/tmux/tmux-menu $(realpath "${files[@]}")
     else
         ${EDITOR} "${files[@]}"
 
@@ -54,6 +59,7 @@ exec_action() {
 
 main() {
     [[ $# -gt 1 && "$1" == help ]] && help
+    [[ -v TMUX && $(command -v fzf-tmux) ]] && fzf_bin="fzf-tmux $FZF_TMUX_OPTS"
 
     # 判断是否是一个git目录
     if ! git rev-parse --is-inside-work-tree &> /dev/null; then
@@ -65,25 +71,48 @@ main() {
 
     # args
     typeset -a git_flags
-    while getopts "mdksio" opt; do
-        case $opt in
-        m)
+    typeset args
+
+    args=$(getopt -o mdskio -l no-popup -n "$0" -- "$@")
+    if [[ "$?" -ne 0 ]]; then
+        echo "getopt parse error, args:${*}"
+        exit 1
+    fi
+    eval set -- "$args"
+
+    while true; do
+        case $1 in
+        --no-popup)
+            fzf_bin=
+            shift
+            ;;
+        -m)
             git_flags+=("--modified")
+            shift
             ;;
-        d)
+        -d)
             git_flags+=("--deleted")
+            shift
             ;;
-        s)
+        -s)
             git_flags+=("--stage")
+            shift
             ;;
-        k)
+        -k)
             git_flags+=("--killed")
+            shift
             ;;
-        i)
+        -i)
             git_flags+=("--ignored")
+            shift
             ;;
-        o)
+        -o)
             git_flags+=("--others")
+            shift
+            ;;
+        --)
+            shift
+            break
             ;;
         *)
             echo "flag error"
@@ -92,9 +121,8 @@ main() {
 
         esac
     done
-    shift $((OPTIND - 1))
 
-    [[ -v TMUX && $(command -v fzf-tmux) && $# -eq 0 ]] && fzf_bin="fzf-tmux $FZF_TMUX_OPTS"
+    [[ $# -gt 0 && ${fzf_bin} ]] && fzf_bin=
 
     # 得到files
     fzf_search "$@"
diff --git a/fzf/find-oldfiles b/fzf/find-oldfiles
--- a/fzf/find-oldfiles
+++ b/fzf/find-oldfiles
@@ -24,6 +24,9 @@ fzf_search() {
     action=/tmp/$$
     [[ -e $action ]] && exit 1
     trap "command rm -f $action" EXIT SIGINT SIGTERM
+
+    action_e="execute(${EDITOR} {+} > /dev/tty < /dev/tty)"
+
     readarray -t files < <(
         cat "${filterfiles}" | lscolors | ${fzf_bin:-fzf} \
             --prompt="Oldfiles> " ${filter_query:+--filter "${filter_query}"} \
@@ -32,7 +35,8 @@ fzf_search() {
             --header "keybindings: C-s(hsp), C-v(vsp), A-e(fzf-tmux-menu), Enter(select or new file)" \
             --bind="ctrl-s:transform:echo h > $action; echo accept" \
             --bind="ctrl-v:transform:echo v > $action; echo accept" \
-            --bind="alt-e:transform:echo m  > $action; echo accept" \
+            --bind="ctrl-o:transform:echo m > $action; echo accept" \
+            --bind="alt-e:transform:[[ \"${fzf_bin}\" ]] && echo \"ignore\" || echo \"${action_e}\"" \
             --bind="enter:accept-or-print-query" | sed -n "${filter_query:+1}p"
     )
 }
@@ -57,11 +61,39 @@ main() {
 
     typeset filterfiles action files
 
+    typeset args
+
+    args=$(getopt -o z -l no-popup -n "$0" -- "$@")
+    if [[ "$?" -ne 0 ]]; then
+        echo "getopt parse error, args:${*}"
+        exit 1
+    fi
+    eval set -- "$args"
+
+    while true; do
+        case $1 in
+        --no-popup)
+            fzf_bin=
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "flag error"
+            exit 1
+            ;;
+
+        esac
+    done
+
     get_oldfiles
 
     if [[ $# -eq 1 && $1 == - ]]; then
         files=$(sed -n '1p' "${filterfiles}")
     else
+        [[ $# -gt 0 && ${fzf_bin} ]] && fzf_bin=
         fzf_search "$@"
     fi
 
@@ -69,22 +101,3 @@ main() {
 }
 
 main "$@"
-
-# fzf_search() {
-#     action=/tmp/$$
-#     [[ -e $action ]] && exit 1
-#     trap "command rm -f $action" EXIT SIGINT SIGTERM
-#     readarray -t files < <(
-#         ${fzf_bin:-fzf} \
-#             --query "${*}" --prompt="Oldfiles> " \
-#             --scheme history --exact --tiebreak "end,chunk,index" \
-#             --select-1 --exit-0 --header-first \
-#             --header "keybindings: C-x(cp base), C-s(hsp), C-v(vsp), A-e(fzf-tmux-menu), Enter(select or new file)" \
-#             --bind='ctrl-x:transform-query:echo $(dirname {})/' \
-#             --bind="ctrl-s:transform:echo h > $action; echo accept" \
-#             --bind="ctrl-v:transform:echo v > $action; echo accept" \
-#             --bind="alt-e:transform:echo m  > $action; echo accept" \
-#             --bind="enter:accept-or-print-query" \
-#             < <(cat "${filterfiles}" | lscolors)
-#     )
-# }
